name: Docker release build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Get rclone version
        id: get_rclone_version
        run: echo ::set-output name=RCLONE_VERSION::$(head -n1 Dockerfile | sed -n 's/FROM.*\:\(.*\)/\1/p')
      - name: Build and publish image
        uses: ilteoood/docker_buildx@1.1.0
        with:
          tag: latest,${{ steps.get_rclone_version.outputs.RCLONE_VERSION }}
          imageName: jonoh/rclone-serve
          platform: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          publish: ${{ github.ref == 'refs/heads/master' }}
          dockerHubUser: ${{ secrets.DOCKER_HUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.4.3
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: jonoh/rclone-serve
          README_FILEPATH: ./readme.md
